### ISSUE TITLE
Add include / exclude pattern support (regex and/or glob)

### ISSUE THREAD

**Issue by acdvorak** [acdvorak/intellij-lessc-plugin#11]
Match against path or filename

**Comment by denisborovikov** [comment]
Must have feature. My projects have only the one file that needed to be compiled. All other files in this directory are included in the previous one.

**Comment by acdvorak** [comment]
@Metaller: Do the other files in your directory _only_ contain mixins and variables (i.e., stuff that won't produce any output when compiled)?  Or do they actually have rule sets that produce output if you compile the files directly?

I suspect the latter is true, but I want to make sure I understand your use case.

**Comment by denisborovikov** [comment]
@acdvorak twitter bootstrap is a good example of such project. Some files contains mxins and variables, others - less rules. Main file includes all of them via @import and it is only the one file that must be compiled.

Here is an example of main file (bootsrap.less):

``` css
@import "reset.less";
// Core variables and mixins
@import "variables.less"; // Modify this for custom colors, font-sizes, etc
@import "mixins.less";
// Grid system and page structure
@import "scaffolding.less";
@import "grid.less";
@import "layouts.less"; 
```

**Comment by acdvorak** [comment]
Got it.  I'll make this issue my top priority for the next version.  Thanks!

**Comment by denisborovikov** [comment]
Thank you! Your plugin is a great addition to Webstorm.

**Comment by nstawski** [comment]
+1 this request. I am working with Bootstrap files now, and when I edit the included .less files, this plugin tries to compile them (which results in an error), and for the main file I need to run it manually, cause it never gets changed.

It would be great that in addition to the folder for less files you could specify the exact files that should be compiled, so they are recompiled every time any file in the specified folder gets saved.

Thank you for a handy plugin :)

**Comment by acdvorak** [comment]
Feature is now available in [version 2.4.0](http://plugins.jetbrains.com/plugin?pr=&pluginId=7059).  (I haven't checked in the source code to GitHub yet.)  Give it a try and let me know if it works for you.  Thanks!

**Comment by denisborovikov** [comment]
Thank you, Andrew! It works like a charm. 

Unfortunately, I started using sass while waiting for full native less support in tne webstorm. I found some cool features in sass that have no in less and made a final decision for myself.

Good luck for you and your work, many people waited for this plugin.

**Comment by acdvorak** [comment]
No worries Denis!  I'm just glad to hear you found a solution that works for you -- that's what really matters.  Thanks for the feedback and happy coding!

**Comment by nstawski** [comment]
I am using it, and 'Include' works nice, thank you!

What would be even more useful in terms of using this plugin with Bootstrap, is compiling the main file every time any file in the directory has been changed and saved.

For example, I have two main files in the directory that have to be compiled: bootstrap.less and responsive.less.
All others are includes. I don't usually change the main file, I am working on the ones that are @included.

Right now, with the new version of the plugin (that works much better :) ), I put my two main files in the 'Include files by path', and when I change and save the other files, nothing happens. I have to manually go to the main file, and either press 'Compile to CSS', or try changing something there and saving.

If you could eliminate this step, for example, if all my 'Include by path' files were compiling every time I save anything in that directory, it would be saving much much more time.

**Comment by denisborovikov** [comment]
I tested a new version of the plugin with bootstrap and all worked good for me. I set less source directory, css output directory and bootstrap.less in the include files by path. When any of the included files is changed, plugin recompiles bootstrap.css and I've got a message in the log like "LESS CSS Compiler: button-groups.less was modified, but didn't change any CSS files (ignore)" with the name of the changed file.

**Comment by nstawski** [comment]
I get the same message "CSS Compiler: navs.less was modified, but didn't change any CSS files (ignore)", but the main file ("bootstrap.less") isn't getting recompiled when I save changed navs.less.

I have set less source directory, css destination, and bootstrap.less in the 'Include files by path'.

**Comment by nstawski** [comment]
No matter what I try, my main file doesn't compile unless I go and change something in it explicitly or say 'Compile to CSS'.
I tried reinstalling plugin, changing configuration, etc. Nothing works.

Can somebody post a screenshot of their working configuration? Maybe I am not entering something right in 'Include files by path'?

**Comment by nstawski** [comment]
OK, I found what is happening.

In the main file, all @includes are written without ".less". When I add the file extension, everything works.

**Comment by acdvorak** [comment]
Whew!  Glad to hear you figured it out and it wasn't a bug on my part :-p

@nstawski: I'll add a note in the readme mentioning that `@import` filenames w/o extensions are not yet supported as per [your suggestion](https://github.com/acdvorak/intellij-lessc-plugin/issues/6#issuecomment-10346560).  Thanks!
