### ISSUE TITLE
LESS CSS compiler error

### ISSUE THREAD

**Issue by ivankolev** [acdvorak/intellij-lessc-plugin#12]
IDEA spits this:
"file.less: java.io.IOException: No such file C:\Users\myusername\IdeaProjects\myproject\less\file.less"
 when trying to use the plugin. Maybe it's related to the patch Jetbrains pushed today, 11.1.4
I don't know what other info is needed, please advice

**Comment by acdvorak** [comment]
Duplicate of #13 - merging issues
