### ISSUE TITLE
How to compile/install the plugin?

### ISSUE THREAD

**Issue by intmainreturn0** [acdvorak/intellij-lessc-plugin#15]
Hello.
I have been using PhpStorm for a long time, but I have never installed new plugins (like this) from sources. When I tried to do it, I felt so unlucky :)
I have downloaded IDEA 11.1.4 community edition, there I click "File -> Open project", and... it is unable to select iml-files (only folders), OK button in popup "open project" is permanently not activated...

**Comment by acdvorak** [comment]
What was the problem, and how did you solve it?  Someone else might run into the same issue, so it may help others if we document it here.  Thanks!

**Comment by intmainreturn0** [comment]
Well, I just stopped trying to compile it from sources, went to http://plugins.intellij.net/plugin/?idea&pluginId=7059, downloaded and installed :)
