### ISSUE TITLE
Problems with spaces in path name

### ISSUE THREAD

**Issue by ghost** [acdvorak/intellij-lessc-plugin#17]
When using a linux system if you have spaces in a path name eg /home/pete/PhpstormProjects/project name/lessfiles-devonly/style.less

Then you get a compile error

LESS CSS Compiler Error: style.less: java.io.IOException: No such file file:/home/pete/PhpstormProjects/project name/lessfiles-devonly/style.less

remove the space in project name and use projectName then all is ok.

**Comment by acdvorak** [comment]
Pete,

Could you please update the plugin in your IDE and let me know if the issue is resolved?  I tested the fix in Mac OS X (10.6 and 10.7), so it _"should"_ work in Linux as well, but I want to verify that it's working for you before I close the issue permanently.

Thanks!

**Comment by ghost** [comment]
Yep works fine now.

**Comment by acdvorak** [comment]
Great!  Glad to hear it.  Thanks for taking the time to report this issue!
