### ISSUE TITLE
Improve threading speed by reducing unnecessary synchronizations and deadlocks

### ISSUE THREAD

**Issue by acdvorak** [acdvorak/intellij-lessc-plugin#30]

**Comment by acdvorak** [comment]
Not necessary.  Now that Rhino optimizations are enabled, this baby is **wicked** fast.

**Comment by intmainreturn0** [comment]
Are Rhino optimizations turned on by default or we (users) should perform some actions to turn them on? :)

**Comment by acdvorak** [comment]
They're enabled by default in the Java code, so there's no user action required :-D

Previously they were turned off while I worked through some integration issues with [asual's LESS Engine](https://github.com/asual/lesscss-engine), but now that those issues are resolved I figured it was time to speed things up a bit.

You can [read about Rhino's optimization settings](https://developer.mozilla.org/en-US/docs/Rhino/Optimization) on MDN if you're curious; they basically boil down to generating class files, analyzing variables' data types, caching, etc..
