### ISSUE TITLE
When detecting changes, compile main.less only

### ISSUE THREAD

**Issue by jhuesos** [acdvorak/intellij-lessc-plugin#33]
Hi Andrew,

Would it be possible to when the plugin detect a change in one file, compile only an specific file?

The problem I have is in my projects, the way I usually work with LESS is I have a main.less and then I import rest from the files from there. For example

main.less
pages/page1.less
pages/page2.less
...

From main.less I import page1.less and page2.less. And in my site I only load a single file: main.css (a compiled version of main.less with all references).

So what it would be great for me is that every time a change in any file inside the folder is detected, it triggers the compilation of ONLY main.less, and then through the references inside main.less, all of them will be compiled.

Cheers,

**Comment by acdvorak** [comment]
Hey Jaime,

Absolutely!  Set "`Include files by path`" to "`main.less`" in the [settings dialog](https://raw.github.com/acdvorak/intellij-lessc-plugin/master/screenshots/settings.png) (IntelliJ Settings > Project Settings > LESS Compiler).  Changes to child files (e.g., `pages/page1.less`) will trigger `main.less` to be compiled, but the child files themselves will not be compiled.

Hope this helps.  Let me know if you have any other questions or issues!

**Comment by EnzoMartin** [comment]
Was just about to ask how to do this as well, would it be possible for you to add this to the docs? There might be others who were wondering the same thing :+1:
