### ISSUE TITLE
IntelliJ 12 Support

### ISSUE THREAD

**Issue by eukreign** [acdvorak/intellij-lessc-plugin#35]
The "LESS Compiler" menu doesn't show up under IntelliJ 12. Worked fine in 11 until I upgraded to 12.

If you could update the developer/debug instructions maybe I can try debugging it to see why it doesn't show up.

**Comment by rawtaz** [comment]
Any news on this? I'm actually holding back on upgrading IDEA since I don't want this and other plugins to stop working :)

**Comment by malundstrom** [comment]
Also waiting for news on this issue.

**Comment by circmark** [comment]
It works fine in 12. Maybe you have to go back to the repository and download it again

**Comment by acdvorak** [comment]
I just bought IntelliJ IDEA 12.  Hopefully in the next few weeks I'll have a chance test it and make any necessary adjustments.  Sorry for the delay...  I'm pretty slammed at work right now.  But I'm working on it, I promise :-)

**Comment by acdvorak** [comment]
@circmark is right - you just need to download it again from the IDEA plugin manager window.  IntelliJ doesn't keep your custom plugins when you upgrade so you have to re-download them.
