### ISSUE TITLE
LESS files don't compile in Plugin

### ISSUE THREAD

**Issue by EnzoMartin** [acdvorak/intellij-lessc-plugin#39]
I have a bunch of LESS files and they compile just fine using lessc or SimpLESS, however when compiling through the plugin, it just errors.

Here are the LESS files I'm trying to compile: http://www.tech-burrow.com/github/less.zip

**Comment by rawtaz** [comment]
@EnzoMartin78 Which version of IDEA are you running? Could this be a problem specific to IDEA 12, or is that not likely (maybe you have other files that compile just fine with this plugin, or something)?

**Comment by EnzoMartin** [comment]
I'm running on the latest PyCharm (2.6.3) which runs on IDEA12 yea. Could it be the plugin is using an outdated LESS version?

I've tried some other LESS files and they seem to compile fine, but they were fairly small files in comparison to the ones that error on me

**Comment by jamelt** [comment]
I'm having the same problem. I'm using PhpStorm 5.0.4. I edited my LESS files and absolutely nothing happened.

**Comment by acdvorak** [comment]
@EnzoMartin78 I bumped the LESS version from 1.3.1 to 1.3.3 and it fixed the issue.  I'll release a new version of the plugin in the next day or two.  Thanks for the report!

BTW - did you set "Include files by path" in the plugin preference pane to `modern.less;modern-responsive.less` (or something similar)?

**Comment by EnzoMartin** [comment]
Excellent to hear, figured it was probably a version issue.

I actually dropped that CSS library thing, but I think I had it set to only include modern.less. I've been using your plugin for other projects, usually creating a profile for each main LESS file I have and so far it's been fine.

Only other issue is that it doesn't re-compile files that include modified files. (if I have file1.less that includes file2.less and I modify file2.less, file1.less doesn't recompile)

**Comment by acdvorak** [comment]
@EnzoMartin78 I assume you're referring to #44?  Just wanna make sure I don't miss anything.

FYI - I just released version 2.6.2 in the JetBrains plugin repository.  Give it a try and let me know if it indeed solves this issue!

**Comment by EnzoMartin** [comment]
Works perfectly now, nice!

And yes, #44 is the one I'm referring to for the included less files

**Comment by acdvorak** [comment]
Cool!  Glad to hear it's working.  I'll take a look at #44 soon.  Thanks!
