### ISSUE TITLE
Less 1.3.3 ?

### ISSUE THREAD

**Issue by TheoL** [acdvorak/intellij-lessc-plugin#40]
Looking at the file names this plugin seems to be using Less 1.3.1 instead of Less 1.3.3 which is the latest version.

**Comment by acdvorak** [comment]
Bumped LESS version to 1.3.3 in my local Git repo.  I'll release a new version of the plugin in the next day or two.

Thanks!

**Comment by acdvorak** [comment]
v2.6.2 (which includes LESS 1.3.3) is now available in the JetBrains plugin repository.  Give 'er a go!
