### ISSUE TITLE
Name Error: "mixin" is undefined

### ISSUE THREAD

**Issue by MitoZ** [acdvorak/intellij-lessc-plugin#41]
Hi. I use your plugin with webstorm 5.0.4, plugin version is 2.6.1
I have main less file, and some child files wich is imported to main.
for example in main import look like:
@import 'less/variables.less';
@import 'less/min-1200px.less';

I have 1 mixin in variables.less:
.center{
  margin: 0 auto;
}

and i use it in min-1200px.less:

.site-body{
    max-width: 1200px;
    .center;
  }

but plagin wrote error:
LESS CSS Compiler Error
         min-1200px.less: Name Error: .center is undefined

and profile for base.less duplicate in  "LESS Profiles"
if i did not create base.less profile it auto-created .

**Comment by Shaz3e** [comment]
I was having the same problem until the path is correct.

Example:
@import "less/variables"; // the path should be correct with the ./ or ../
@import "less/variables";
@import "less/min-1200px";

I assume that is your main.less file which is also in the same directory less/main.less

.center{
      margin: auto;
}

.site-body{
      max-width:1200px;
      .center;
}

**Comment by acdvorak** [comment]
I'm unable to reproduce the problem.  Sounds like you may be using incorrect paths in your LESS file...  Please reopen this issue if the problem persists after updating to the latest version of the plugin (2.6.7).  Thanks!
