### ISSUE TITLE
Changing less files does not re-compile any other less file that is importing the changed file

### ISSUE THREAD

**Issue by EnzoMartin** [acdvorak/intellij-lessc-plugin#44]
I have a parent Structure.less which imports other less files, when I change the imported less files, the structure.less does not re-compile, forcing me to constantly manually re-compile it

**Comment by 0x46616c6b** [comment]
If you using [Bootstrap](http://twitter.github.com/bootstrap/) you are also affected by this issue.

**Comment by django23** [comment]
Hey Guys,

This problem is still existing. Have you found a workaround?

**Comment by django23** [comment]
The probleem seems to occur when linkink to parent files with ../otherDir
