### ISSUE TITLE
Support runner instead of autocompilation

### ISSUE THREAD

**Issue by ghost** [acdvorak/intellij-lessc-plugin#45]
Sometimes I do not want my file to be recompiled automatically. It would be nice to have runner (SHIFT+F10) or sidebar (like ant plugin has) to allow user to run it by my self

**Comment by acdvorak** [comment]
You can right-click on the file in the editor or the Project panel and choose "Compile to CSS".  If I added an option to disable automatic compilation, would that work for you?  Or would you prefer a keyboard shortcut as well?
