### ISSUE TITLE
Less 1.4.0?

### ISSUE THREAD

**Issue by herrbaehrt** [acdvorak/intellij-lessc-plugin#53]
Looking for the current less version in github-repro https://github.com/cloudhead/less.js i noticed there was the less 1.4.0 release 7 days ago. Is there an update coming up?

**Comment by bjorn2404** [comment]
This would be really useful. It's been month and I'd like for this to compile with &:extend();

**Comment by rolandtoth** [comment]
+1 for the update

**Comment by jankus** [comment]
Waiting for update, too. Killer feature is forcing compiler to compile CSS file as LESS:

``` css
@import (less) "file.css";
```

This is important for namespacing. Workaround works only 1.4+ http://stackoverflow.com/a/19796985/1448988

**Comment by acdvorak** [comment]
I would love to do this, but unfortunately they stopped releasing Rhino-compatible versions of less.js, which means I would need to completely rewrite the plugin to interface directly with Node.js.  Sadly I don't have the time to do that, but contributions are **always** welcome :-)

**Comment by acdvorak** [comment]
I take it back - @asual updated asual/lesscss-engine@821187b8f383f3ec0df97952878535abfa8ab71b to support 1.5.0, which I then updated to 1.6.0 in commit 604d9a14161e3a82f4b3023d4f243a5c0c14150e.

The plugin as been updated to LESS 1.6.0 in the official IntelliJ repository.  Enjoy!  :-)

**Comment by thinkspill** [comment]
Does this mean #56 Source Map support is possible as well?

**Comment by acdvorak** [comment]
Yes, it should be possible.  I'm a **huge** fan of source maps, and would _love_ to add support for them.  At this point it's simply a matter of when I'll have time to implement it properly.
