### ISSUE TITLE
Possibility to disable auto-compilation on every save (trigger it manually)

### ISSUE THREAD

**Issue by grubersjoe** [acdvorak/intellij-lessc-plugin#58]
On low level hardware and large LESS files the compilation can take a while and interrupt you in your workflow. I would like to have the possibility to trigger the compilation manually (through the right click menu for instance), instead of the current behaviour, that the file gets compiled on every save.

I know, I simply could save less often, but I'm the kind of person, who got used to save many many times. So I think this feature would be pretty useful :).

**Comment by chenasraf** [comment]
You can turn off the profile's source directory and add a shortcut in the keymap to the "Compile to CSS" action... that's what I do

**Comment by grubersjoe** [comment]
Thanks, I feel a bit stupid right now, not to think about this ^^. However, now I have the same error you have opened a new issue about #59 .

**Comment by chenasraf** [comment]
Figured how to solve it; put the source and destination as you need,
but exclude/don't include the less files in the proper field, and only
manually do it from there
