### ISSUE TITLE
Optional .less extension support for @imports

### ISSUE THREAD

**Issue by acdvorak** [acdvorak/intellij-lessc-plugin#6]
Support both `@import "lib"` and `@import "lib.less"`

**Comment by nstawski** [comment]
While it's not yet working, you could just add a line to ReadMe that you should use '.less' with your @import names.

**Comment by acdvorak** [comment]
You got it.  Great suggestion.  Thanks!

Where would you recommend I put it in the readme so that it's easy to spot but not too obtrusive?

**Comment by acdvorak** [comment]
Available in v2.5.1.  Turns out it was super easy to do.  Woot woot!
