### ISSUE TITLE
Fubar - how to uninstall, re-install?

### ISSUE THREAD

**Issue by mbcooper** [acdvorak/intellij-lessc-plugin#60]
I was getting the following error using the plug-in:

Program Files (x86)\JetBrains\IntelliJ IDEA 12.1.6\plugins\less\lib\less.jar" --no-color ourApp.less
no main manifest attribute, in C:\Program Files (x86)\JetBrains\IntelliJ IDEA 12.1.6\plugins\less\lib\less.jar

So I blew away the folder, and tried to re-install.  It still showed up in the plug-in list in Setiings, so I deleted it.

No I cannot add it back from the jetBrains repository!

help!

**Comment by acdvorak** [comment]
I'm not sure how to fix that; you'd need to contact [JetBrains Support](https://intellij-support.jetbrains.com/home).
