### ISSUE TITLE
Cannot get rid of a profile

### ISSUE THREAD

**Issue by dlgski** [acdvorak/intellij-lessc-plugin#61]
I created a profile and applied it.  Afterwards I realized I needed to change it (added an Include file) clicked "Apply" then "Save".

I went to test my compilation and it still did the functions of the previous profile.  So I opened my preferences again and now I had 2 profiles, one the original setting and a second the new settings. Both with the same name.  I deleted the incorrect one, Applied & tested, same problem.  Went back to preferences, and again, it was back.  I cannot get rid of it!   I tried removing both and creating a new one with a different name.  Same problem, the original one came back.

I removed LESS CSS Compiler from my plugins, restarted WebStorm and then re-added the plugin again.  Set up the new profile, clicked on Apply and tested.   Went back to preferences, and that original profile was back!

Where on my file system are these profiles saved?  Can I delete the old profile from somewhere so it will stop coming back?

Thanks

**Comment by acdvorak** [comment]
You should be able to edit the plugin preferences manually; they're stored in `.idea/lessc/lessc.xml` in your project directory.  Make sure to exit the IDE before making any changes to avoid conflicts.
